# Generated by Django 5.2.1 on 2025-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='movies/imagenes/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
