# Generated by Django 5.2.1 on 2025-08-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_director_remove_movie_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movie/images/default.jpg', null=True, upload_to='movie/images/'),
        ),
    ]
